### ISSUE TITLE
¿`Ascension.cost` es opcional?

### ISSUE THREAD

**Issue by Victorsitou** [dvaJi/genshin-data#10]
En los archivos JSON, el ascenso de personaje `0 -> 1` no tiene el campo `cost`. ¿Es que el type `Ascension.cost` está incorrecto o el archivo JSON le falta ese campo?

Muy buen repositorio. 👏

**Comment by dvaJi** [comment]
Si, es opcional en el primer ascenso. Esto fue corregido en el último commit.
