### ISSUE TITLE
Why is there duplicate data? Which ID should be used?

### ISSUE THREAD

**Issue by sjlei** [dvaJi/genshin-data#7]
https://github.com/dvaJi/genshin-data/blob/914177f9752ba62ba988b21eb27b51bf5ea044ed/src/data/english/achievements/wonders_of_the_world.json#L2216-L2223

https://github.com/dvaJi/genshin-data/blob/914177f9752ba62ba988b21eb27b51bf5ea044ed/src/data/english/achievements/wonders_of_the_world.json#L114-L121

**Comment by dvaJi** [comment]
You're right, this duplicated data is because the data importer was not using the `isDisuse` property to filter those. This is fixed in https://github.com/dvaJi/genshin-data/releases/tag/0.20.1

**Comment by sjlei** [comment]
Great, thank you so much!
